const DB={get(k){try{return JSON.parse(localStorage.getItem("cb_"+k))||[]}catch{return[]}},set(k,v){localStorage.setItem("cb_"+k,JSON.stringify(v))},_id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)},today(){return new Date().toISOString().slice(0,10)}}
function seedSampleData(){if(getCabinet().length||getRecipes().length)return;const spirits=[{type:"金酒",brand:"孟买蓝宝石",openedDate:"2026-03-10",total:750,remaining:620,unit:"ml"},{type:"金酒",brand:"添加利",openedDate:"2026-05-01",total:750,remaining:750,unit:"ml"},{type:"威士忌",brand:"杰克丹尼",openedDate:"2026-02-15",total:700,remaining:430,unit:"ml"},{type:"威士忌",brand:"尊美醇",openedDate:"2026-04-20",total:700,remaining:700,unit:"ml"},{type:"白朗姆酒",brand:"百加得",openedDate:"2026-01-08",total:750,remaining:280,unit:"ml"},{type:"伏特加",brand:"绝对",openedDate:"2026-03-22",total:750,remaining:550,unit:"ml"},{type:"龙舌兰",brand:"奥美加",openedDate:"2026-05-15",total:750,remaining:720,unit:"ml"},{type:"甜味美思",brand:"马天尼红",openedDate:"2026-04-01",total:750,remaining:500,unit:"ml"},{type:"干味美思",brand:"马天尼干",openedDate:"2026-04-01",total:750,remaining:680,unit:"ml"},{type:"橙皮利口酒",brand:"君度",openedDate:"2026-02-20",total:700,remaining:410,unit:"ml"},{type:"苦精",brand:"安高天娜",openedDate:"2025-12-01",total:200,remaining:160,unit:"ml"},{type:"青柠汁",brand:"新鲜青柠",openedDate:DB.today(),total:200,remaining:200,unit:"ml"},{type:"柠檬汁",brand:"新鲜柠檬",openedDate:DB.today(),total:200,remaining:200,unit:"ml"},{type:"糖浆",brand:"莫林",openedDate:"2026-01-15",total:500,remaining:350,unit:"ml"},{type:"苏打水",brand:"怡泉",openedDate:"2026-06-10",total:330,remaining:330,unit:"ml"},{type:"番茄汁",brand:"Römerquelle",openedDate:"2026-06-01",total:300,remaining:300,unit:"ml"},{type:"金巴利",brand:"金巴利",openedDate:"2026-03-05",total:700,remaining:460,unit:"ml"}]
spirits.forEach(s=>{const i=getCabinet();i.push({id:DB._id(),...s});setCabinet(i)})
const recipes=[{name:"尼格罗尼",glass:"古典杯",instructions:"将所有配料加冰搅拌约20秒，滤入古典杯加冰。橙皮装饰。",garnish:"橙皮",ingredients:[{name:"金酒",amount:30,unit:"ml"},{name:"金巴利",amount:30,unit:"ml"},{name:"甜味美思",amount:30,unit:"ml"}]},{name:"马天尼",glass:"马天尼杯",instructions:"加冰搅拌金酒和干味美思约20秒，滤入冰过的马天尼杯。",garnish:"橄榄或柠檬皮",ingredients:[{name:"金酒",amount:60,unit:"ml"},{name:"干味美思",amount:10,unit:"ml"}]},{name:"古典",glass:"古典杯",instructions:"杯中放糖浆和苦精，加大块冰，倒入威士忌搅拌。橙皮装饰。",garnish:"橙皮",ingredients:[{name:"威士忌",amount:60,unit:"ml"},{name:"糖浆",amount:5,unit:"ml"},{name:"苦精",amount:2,unit:"dash"}]},{name:"莫吉托",glass:"海波杯",instructions:"青柠、薄荷和糖浆捣压，加碎冰，倒朗姆酒，苏打水补满。",garnish:"薄荷枝",ingredients:[{name:"白朗姆酒",amount:45,unit:"ml"},{name:"青柠汁",amount:20,unit:"ml"},{name:"糖浆",amount:15,unit:"ml"},{name:"苏打水",amount:80,unit:"ml"}]},{name:"威士忌酸",glass:"酸酒杯",instructions:"所有材料加冰用力摇约15秒，滤入冰过的酸酒杯。",garnish:"樱桃",ingredients:[{name:"威士忌",amount:50,unit:"ml"},{name:"柠檬汁",amount:25,unit:"ml"},{name:"糖浆",amount:15,unit:"ml"}]},{name:"玛格丽特",glass:"玛格丽特杯",instructions:"杯口蘸盐边。所有材料加冰摇匀滤入。",garnish:"盐边+青柠角",ingredients:[{name:"龙舌兰",amount:45,unit:"ml"},{name:"橙皮利口酒",amount:20,unit:"ml"},{name:"青柠汁",amount:15,unit:"ml"}]},{name:"金汤力",glass:"海波杯",instructions:"加冰，倒金酒，苏打水补满，轻搅。",garnish:"青柠角",ingredients:[{name:"金酒",amount:50,unit:"ml"},{name:"苏打水",amount:120,unit:"ml"}]},{name:"得其利",glass:"鸡尾酒杯",instructions:"所有材料加冰用力摇匀，滤入冰过的鸡尾酒杯。",garnish:"",ingredients:[{name:"白朗姆酒",amount:50,unit:"ml"},{name:"青柠汁",amount:20,unit:"ml"},{name:"糖浆",amount:15,unit:"ml"}]},{name:"血腥玛丽",glass:"海波杯",instructions:"加冰倒入所有材料轻轻摇匀，滤入装冰杯中。",garnish:"芹菜杆+柠檬角",ingredients:[{name:"伏特加",amount:45,unit:"ml"},{name:"番茄汁",amount:90,unit:"ml"},{name:"柠檬汁",amount:10,unit:"ml"}]}]
recipes.forEach(r=>{const i=getRecipes();i.push({id:DB._id(),...r,createdAt:DB.today()});setRecipes(i)})}
function resetSampleData(){if(!confirm("清空所有数据并重新加载示例数据？"))return;Object.keys(localStorage).filter(k=>k.startsWith("cb_")).forEach(k=>localStorage.removeItem(k));seedSampleData();renderCabinet();renderRecipes();renderLog();document.getElementById("shake-result").innerHTML="";document.getElementById("search-results").innerHTML="";toast("已重置","ok")}
function getCabinet(){return DB.get("cabinet")}
function setCabinet(d){DB.set("cabinet",d);renderCabinet();updateTypeSuggest()}
function renderCabinet(){const l=document.getElementById("cabinet-list"),items=getCabinet();if(!items.length){l.innerHTML="<div class=empty-state><div class=empty-icon>🍾</div><p>酒柜还是空的</p></div>";return}
l.innerHTML=items.map(i=>{const p=Math.round((i.remaining/i.total)*100);let c="progress-fill";if(p<=20)c+=" low";else if(p<=40)c+=" mid";return "<div class=item><div class=item-info><div class=item-name>"+esc(i.type)+" <span style=font-weight:400;font-size:.82rem;color:var(--text2)>"+esc(i.brand)+"</span></div><div class=item-brand><span>📅 "+i.openedDate+"</span></div><div class=item-meta>剩余 "+i.remaining+" / "+i.total+" ml</div><div class=progress-bar><div class='"+c+"' style=width:"+p+"%></div></div></div><div class=item-actions><button class=btn-icon onclick=editCabinet(\""+i.id+"\") title=编辑>✏️</button><button class=btn-icon onclick=deleteCabinet(\""+i.id+"\") title=删除>🗑️</button></div></div>"}).join("")}
function showCabinetModal(d){d=d||{};document.getElementById("cabinet-modal-title").textContent=d.id?"编辑酒":"添加酒";document.getElementById("cabinet-edit-id").value=d.id||"";document.getElementById("cabinet-type").value=d.type||"";document.getElementById("cabinet-brand").value=d.brand||"";document.getElementById("cabinet-date").value=d.openedDate||DB.today();document.getElementById("cabinet-total").value=d.total||"";document.getElementById("cabinet-remaining").value=d.remaining||"";showModal("cabinet")}
function saveCabinet(){const id=document.getElementById("cabinet-edit-id").value;const type=document.getElementById("cabinet-type").value.trim();const brand=document.getElementById("cabinet-brand").value.trim();const openedDate=document.getElementById("cabinet-date").value;const total=parseFloat(document.getElementById("cabinet-total").value);const remaining=parseFloat(document.getElementById("cabinet-remaining").value);if(!type||!brand||!total||remaining===undefined){toast("请填写完整","warn");return}if(remaining>total){toast("剩余不能大于总量","warn");return}
const items=getCabinet();if(id){const idx=items.findIndex(i=>i.id===id);if(idx>-1)items[idx]={...items[idx],type,brand,openedDate,total,remaining}}else items.push({id:DB._id(),type,brand,openedDate,total,remaining,unit:"ml"});setCabinet(items);closeModal("cabinet");toast(id?"已更新":"已添加","ok")}
function editCabinet(id){const i=getCabinet().find(i=>i.id===id);if(i)showCabinetModal(i)}
function deleteCabinet(id){if(!confirm("确定删除？"))return;setCabinet(getCabinet().filter(i=>i.id!==id));toast("已删除","ok")}
function updateTypeSuggest(){const t=[...new Set(getCabinet().map(i=>i.type))];document.getElementById("type-suggest").innerHTML=t.map(t=>"<option value=\""+esc(t)+"\">").join("")}
function getRecipes(){return DB.get("recipes")}
function setRecipes(d){DB.set("recipes",d);renderRecipes()}
function renderRecipes(){const l=document.getElementById("recipe-list"),r=getRecipes();if(!r.length){l.innerHTML="<div class=empty-state><div class=empty-icon>📖</div><p>还没有配方</p></div>";return}
l.innerHTML=r.map(x=>"<div class=recipe-preview onclick=viewRecipe(\""+x.id+"\")><div class=recipe-preview-header><span class=recipe-preview-name>🍸 "+esc(x.name)+"</span><div class=item-actions onclick=event.stopPropagation()><button class=btn-icon onclick=editRecipe(\""+x.id+"\") title=编辑>✏️</button><button class=btn-icon onclick=deleteRecipe(\""+x.id+"\") title=删除>🗑️</button></div></div><div class=recipe-preview-meta>"+x.ingredients.length+" 种 · "+(x.glass||"未选杯型")+"</div><div class=recipe-preview-tags>"+x.ingredients.slice(0,4).map(i=>"<span class=tag>"+esc(i.name)+"</span>").join("")+(x.ingredients.length>4?"<span class=tag>+"+(x.ingredients.length-4)+"</span>":"")+"</div></div>").join("")}
function saveRecipe(){const id=document.getElementById("recipe-edit-id").value,name=document.getElementById("recipe-name").value.trim();const glass=document.getElementById("recipe-glass").value.trim(),inst=document.getElementById("recipe-instructions").value.trim();const garnish=document.getElementById("recipe-garnish").value.trim();const rows=document.querySelectorAll(".ingredient-row"),ings=[];rows.forEach(r=>{const n=r.querySelector(".ing-name").value.trim(),a=parseFloat(r.querySelector(".ing-amount").value),u=r.querySelector(".ing-unit").value.trim()||"ml";if(n&&a)ings.push({name:n,amount:a,unit:u})});if(!name||!ings.length){toast("请填写名称和至少一种配料","warn");return}
const items=getRecipes();if(id){const idx=items.findIndex(i=>i.id===id);if(idx>-1)items[idx]={...items[idx],name,glass,instructions:inst,garnish,ingredients:ings}}else items.push({id:DB._id(),name,glass,instructions:inst,garnish,ingredients:ings,createdAt:DB.today()});setRecipes(items);closeModal("recipe");toast(id?"已更新":"已添加","ok")}
function viewRecipe(id){const r=getRecipes().find(i=>i.id===id);if(!r)return;switchView("shake");showShakeDetail(r)}
function editRecipe(id){const r=getRecipes().find(i=>i.id===id);if(!r)return;document.getElementById("recipe-modal-title").textContent="编辑配方";document.getElementById("recipe-edit-id").value=id;document.getElementById("recipe-name").value=r.name;document.getElementById("recipe-glass").value=r.glass||"";document.getElementById("recipe-instructions").value=r.instructions||"";document.getElementById("recipe-garnish").value=r.garnish||"";document.getElementById("ingredient-list").innerHTML="";r.ingredients.forEach(i=>addIngredientField(i.name,i.amount,i.unit));if(!r.ingredients.length)addIngredientField();showModal("recipe")}
function deleteRecipe(id){if(!confirm("确定删除？"))return;setRecipes(getRecipes().filter(i=>i.id!==id));toast("已删除","ok")}
function showRecipeModal(){document.getElementById("recipe-modal-title").textContent="添加配方";document.getElementById("recipe-edit-id").value="";document.getElementById("recipe-name").value="";document.getElementById("recipe-glass").value="";document.getElementById("recipe-instructions").value="";document.getElementById("recipe-garnish").value="";document.getElementById("ingredient-list").innerHTML="";addIngredientField();showModal("recipe")}
function addIngredientField(n,a,u){if(u===undefined)u="ml";if(n===undefined)n="";if(a===undefined)a="";const d=document.createElement("div");d.className="form-row ingredient-row";d.style.marginBottom="8px";d.innerHTML="<input class=ing-name placeholder=名称 value=\""+esc(n)+"\" style=flex:2><input class=ing-amount type=number placeholder=用量 value="+a+" style=flex:1;width:70px min=0 step=5><input class=ing-unit placeholder=ml value=\""+esc(u)+"\" style=width:50px;flex:none><button class=btn-icon onclick=this.parentElement.remove() title=移除>✕</button>";document.getElementById("ingredient-list").appendChild(d)}
function randomDrink(){const r=getRecipes(),el=document.getElementById("shake-result");if(!r.length){el.innerHTML="<div class=empty-state><div class=empty-icon>🍸</div><p>还没有配方</p></div>";return};showShakeDetail(r[Math.floor(Math.random()*r.length)])}
function showShakeDetail(r){const miss=checkMissing(r);const el=document.getElementById("shake-result");let q=String.fromCharCode(34);let html="<div class=random-result><div style=font-size:3rem;margin-bottom:8px>🎲</div><div class=random-name>"+esc(r.name)+"</div>";if(r.glass)html+="<div class=random-glass>🍸 "+esc(r.glass)+"</div>";html+="<div class=random-ingredients><h4>🥃 配料</h4><ul>"+r.ingredients.map(i=>"<li>"+esc(i.name)+" — "+i.amount+" "+(i.unit||"ml")+(miss.find(x=>x.name===i.name)?" <span class=missing-badge>缺</span>":"")+"</li>").join("")+"</ul></div><div class=random-instructions><h4>👨‍🍳 做法</h4><p>"+(r.instructions||"暂无")+"</p></div>";if(r.garnish)html+="<div class=random-instructions><h4>🌿 装饰</h4><p>"+esc(r.garnish)+"</p></div>";if(miss.length)html+="<div style=background:#fff5f5;border:1px solid #f5c6cb;border-radius:8px;padding:12px;margin:16px 0;text-align:center;font-size:.85rem;color:var(--warn)>⚠️ 缺少 "+miss.map(m=>esc(m.name)).join("、")+"<br><span style=font-size:.78rem>材料不足，换一杯吧</span></div>";html+="<div class=random-actions><button class=btn-outline onclick=randomDrink()>🔄 换一杯</button>";if(!miss.length)html+="<button class=btn-primary onclick=makeDrink("+q+r.id+q+")>🥂 干了这杯！</button>";html+="</div></div>";el.innerHTML=html}
let searchMode="name";document.querySelectorAll("#search-tabs button").forEach(b=>{b.addEventListener("click",()=>{document.querySelectorAll("#search-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");searchMode=b.dataset.mode;document.getElementById("search-input").placeholder=searchMode==="name"?"输入鸡尾酒名称...":"输入基酒名称..."})})
function doSearch(){const q=document.getElementById("search-input").value.trim().toLowerCase();const el=document.getElementById("search-results"),all=getRecipes();if(!q){el.innerHTML="<div class=empty-state><div class=empty-icon>🔍</div><p>输入关键词搜索</p></div>";return};const res=searchMode==="name"?all.filter(r=>r.name.toLowerCase().includes(q)):all.filter(r=>r.ingredients.some(i=>i.name.toLowerCase().includes(q)));if(!res.length){el.innerHTML="<div class=empty-state><div class=empty-icon>🔍</div><p>没有找到匹配的配方</p></div>";return};let q2=String.fromCharCode(34);el.innerHTML="<p style=font-size:.82rem;color:var(--text2);margin-bottom:12px>找到 "+res.length+" 个</p>"+res.map(r=>{const m=checkMissing(r);return "<div class=recipe-preview><div class=recipe-preview-header><span class=recipe-preview-name>🍸 "+esc(r.name)+"</span></div><div class=recipe-preview-meta>"+r.ingredients.map(i=>esc(i.name)).join(" · ")+"</div><div class=recipe-preview-tags style=margin-top:4px>"+(m.length?"<span style=color:var(--warn);font-size:.78rem>⚠️ 缺 "+m.map(x=>esc(x.name)).join("、")+"</span>":"<span style=color:var(--ok);font-size:.78rem>✅ 材料齐全</span>")+"</div><div class=search-actions><button class=btn-outline onclick=viewRecipe("+q2+r.id+q2+")>查看配方</button>"+(m.length?"":"<button class=btn-primary onclick=makeDrink("+q2+r.id+q2+")>做这杯</button>")+"</div></div>"}).join("")}
function checkMissing(r){const cab=getCabinet();return r.ingredients.filter(ing=>{const match=cab.filter(c=>c.type===ing.name&&c.remaining>=ing.amount);return!match.length}).map(m=>({name:m.name}))}
function getAvailBrands(t,amt){return getCabinet().filter(c=>c.type===t&&c.remaining>=amt)}
let pendingMake=null;let brandSels={}
function makeDrink(rid){const r=getRecipes().find(x=>x.id===rid);if(!r)return;const miss=checkMissing(r);if(miss.length){toast("⚠️ 缺少 "+miss.map(m=>m.name).join("、")+"，换一杯吧","warn");return};const multi=[];r.ingredients.forEach(ing=>{const b=getAvailBrands(ing.name,ing.amount);if(b.length>1)multi.push({name:ing.name,brands:b,amount:ing.amount,unit:ing.unit})});if(multi.length){pendingMake=rid;showBrandPick(r,multi)}else{executeMake(r,{})}}
function showBrandPick(r,multi){document.getElementById("brand-recipe-name").textContent="为「"+r.name+"」选择品牌";const list=document.getElementById("brand-pick-list");brandSels={};let q=String.fromCharCode(34);list.innerHTML=multi.map(m=>{const sid="bs_"+m.name.replace(/\s/g,"");brandSels[m.name]=m.brands[0].id;return "<div class=brand-pick-item><label>"+esc(m.name)+"（需要 "+m.amount+" "+m.unit+"）</label><select id="+sid+">"+m.brands.map(b=>"<option value="+q+b.id+q+">"+esc(b.brand)+"（剩 "+b.remaining+" ml）</option>").join("")+"</select></div>"}).join("");setTimeout(()=>{multi.forEach(m=>{const sel=document.getElementById("bs_"+m.name.replace(/\s/g,""));if(sel)sel.addEventListener("change",()=>{brandSels[m.name]=sel.value})})},50);showModal("brand")}
function confirmBrandPick(){closeModal("brand");if(pendingMake)executeMake(getRecipes().find(r=>r.id===pendingMake),brandSels);pendingMake=null}
function executeMake(r,bm){const cab=getCabinet();r.ingredients.forEach(ing=>{const b=getAvailBrands(ing.name,ing.amount);let t;if(b.length===1)t=b[0];else t=cab.find(c=>c.id===bm[ing.name]);if(t)t.remaining=Math.round((t.remaining-ing.amount)*10)/10});setCabinet(cab);const log=getLog();log.unshift({id:DB._id(),recipeName:r.name,recipeId:r.id,drankAt:new Date().toISOString(),ingredients:r.ingredients.map(i=>({...i}))});setLog(log);toast("🥂 干杯！已扣减库存","ok")}
function getLog(){return DB.get("log")}
function setLog(d){DB.set("log",d);renderLog()}
function renderLog(){const l=document.getElementById("log-list"),items=getLog();if(!items.length){l.innerHTML="<div class=empty-state><div class=empty-icon>📋</div><p>还没有记录</p></div>";return};l.innerHTML=items.map(e=>{const d=new Date(e.drankAt);let q=String.fromCharCode(34);return "<div class=log-entry><div><div class=log-name>🥂 "+esc(e.recipeName)+"</div><div class=log-date>"+d.toLocaleDateString("zh-CN")+" "+d.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})+" · "+e.ingredients.length+" 种</div></div><button class=btn-icon onclick=deleteLog("+q+e.id+q+") title=删除>🗑️</button></div>"}).join("")}
function deleteLog(id){if(!confirm("删除这条？"))return;setLog(getLog().filter(e=>e.id!==id));toast("已删除","ok")}
function clearLog(){if(!confirm("清空所有记录？"))return;setLog([]);toast("已清空","ok")}
function showModal(t){document.getElementById("modal-"+t).classList.add("active")}
function closeModal(t){document.getElementById("modal-"+t).classList.remove("active")}
document.querySelectorAll(".modal-overlay").forEach(el=>{el.addEventListener("click",e=>{if(e.target===el)el.classList.remove("active")})})
document.querySelectorAll("#nav button").forEach(b=>{b.addEventListener("click",()=>switchView(b.dataset.view))})
function switchView(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.getElementById("view-"+v).classList.add("active");document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="shake")randomDrink()}
document.getElementById("btn-add-cabinet").addEventListener("click",()=>showCabinetModal())
document.getElementById("btn-add-recipe").addEventListener("click",()=>showRecipeModal())
document.getElementById("btn-reroll").addEventListener("click",()=>randomDrink())
document.getElementById("btn-search").addEventListener("click",()=>doSearch())
document.getElementById("btn-clear-log").addEventListener("click",()=>clearLog())
document.getElementById("btn-reset-data").addEventListener("click",()=>resetSampleData())
document.getElementById("search-input").addEventListener("keydown",e=>{if(e.key==="Enter")doSearch()})
function toast(m,t){if(t===undefined)t="";const e=document.getElementById("toast");e.textContent=m;e.className="toast show "+t;clearTimeout(e._timer);e._timer=setTimeout(()=>e.classList.remove("show"),2500)}
function esc(s){if(!s)return"";const d=document.createElement("div");d.textContent=s;return d.innerHTML}
seedSampleData();renderCabinet();renderRecipes();renderLog();updateTypeSuggest()
